/*
 * Generated by MTK SP DrvGen Version 03.13.0 for MT6572_NP. Copyright MediaTek Inc. (C) 2013.
 * Tue Jan 19 18:43:14 2016
 * Do Not Modify the File.
 */

#ifndef __CUST_AUXADC_TOOL_H
#define __CUST_AUXADC_TOOL_H




#endif //_CUST_AUXADC_TOOL_H


