/*
 * Generated by MTK SP DrvGen Version 03.13.0 for MT6572_NP. Copyright MediaTek Inc. (C) 2013.
 * Tue Jan 19 18:43:14 2016
 * Do Not Modify the File.
 */

#define GPIO_DVDD28_BPI     GPIO_VIO28
#define GPIO_DVDD3_LCD     GPIO_VIO28
#define MSDC_POWER_MC1     MSDC_VMC


