#jiangjingjing add 20150129 for defect 127326
ifeq ($(NMI_MATV_AUD_SUPPORT),yes)	
ccflags-y += -DNMI5625	
endif
#jiangjingjing add 20150129 for defect 127326

obj-$(CONFIG_MTK_SOUND) += AudDrv_Kernel.o AudDrv_Clk.o AudDrv_Afe.o AudDrv_Ana.o
